# Generated by Django 2.2 on 2019-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190505_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nmb',
            field=models.IntegerField(default=1),
        ),
    ]
